apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deploy
  labels:
    app: boardgame
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  replicas: 3 # Increased for higher availability
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: shedyvince29/boardshack:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
  labels:
    app: boardgame
spec:
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80        # Exposed port
      targetPort: 8080 # Container port
  type: LoadBalancer
